### ISSUE TITLE
ImageContentSourcePolicy restarts all worker nodes.

### ISSUE THREAD

**Issue by cdjohnson** [openshift/machine-config-operator#1342]
**Description**
Updating any ImageContentSourcePolicy retarts all of the worker nodes.

This is very intrusive if the policies are updated frequently.

**Steps to reproduce the issue:**
1.  From a client....
    1. `oc login -u kubeadmin -p <password> ...`
    1. Create an ImageContentSourcePolicy as follows:
        ```
        cat <<EOF | oc apply -f -
        apiVersion: operator.openshift.io/v1alpha1
        kind: ImageContentSourcePolicy
        metadata:
          name: icsptest
        spec:
          repositoryDigestMirrors:
          - mirrors:
            - image-registry.openshift-image-registry.svc:5000/imageregistry/nginx
            source: fakeregistry1.local/imageregistry/nginx
        EOF
        ```
    1. Run `oc get nodes` and you will see the worker nodes removed from scheduling and restarted.

**Describe the results you received:**
The worker nodes are drained and restarted.

**Describe the results you expected:**
The worker nodes should not be restarted.  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**
```
machine-config-operator                       https://github.com/openshift/machine-config-operator                       62b0b6d2a751a5f364f2e6d5c9cfe63419668777
```

**Additional environment details (platform, options, etc.):**
