### ISSUE TITLE
Applying ImageContentSourcePolicy makes openshift cluster down

### ISSUE THREAD

**Issue by bybywudi2** [openshift/machine-config-operator#1354]
**Description**

**Steps to reproduce the issue:**
1.according to this article: https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.html
2.create a ImageContentSourcePolicy file named proxy-redh-iscp.yaml 
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: proxyv2-rhel8
spec:
  repositoryDigestMirrors:
  - mirrors:
    - image-registry.openshift-image-registry.svc:5000/openshift/proxyv2-rhel8
    source: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8
```
3.
after executing
```
oc apply -f proxy-redh-iscp.yaml 
```
All of the nodes are down
