### ISSUE TITLE
Machineconfig does not check for duplicate entries in files/units

### ISSUE THREAD

**Issue by yuqi-zhang** [openshift/machine-config-operator#1440]
**Description**

Today if you apply 2 machineconfigs that write contents to the same file via an ignition snippet, they both get rendered into the final `rendered-xxx` config. Then when an update happens, the files are written in order in the rendered config, so whichever one is rendered in later would overwrite the previous.

For example, lets say I have 2 machineconfigs attempting to write a file `/home/core/test`. If you view the rendered config, this should be what you see:

```
      - contents:
          source: data:,hello%20world%0A
          verification: {}
        filesystem: root
        mode: 420
        path: /home/core/test
      - contents:
          source: data:,hello%20coreos%0A
          verification: {}
        filesystem: root
        mode: 420
        path: /home/core/test
```

And when everything has applied you will see one file at `/home/core/test` with `hello coreos` as the content, since it applied in order.

Similarly, since we process units after files, if you have a file snippet writing to the same place as a systemd unit, the unit will overwrite the file. This is technically "correct" and is inline with what you would expect from ignition 0.x, but may cause unexpected behaviour in edge cases, e.g. if you tried to update a unit file with `files` section, it will not apply due to being overwritten.

This originates as a spec issue in ignition v0s2 where duplication is not handled properly, and is fixed in ignition spec 3. Since we are looking to move to spec 3, this duplication will NOT be allowed during upgrades to ignition spec 3 as the translator https://github.com/coreos/ign-converter will be rejecting duplication in units/files.

A quick fix for compatibility with ignition spec 3 is to just have the final rendered config contain the latest source of a file, and not all versions of the file, by just saving the latest source in the final rendered config. This doesn't address that duplication is a potential hazard for weird edge behaviour in general, so we should consider properly addressing duplicated entries.

cc @runcom
