### ISSUE TITLE
shared pull-secret breaks clusters

### ISSUE THREAD

**Issue by mjudeikis** [openshift/machine-config-operator#1718]
On managed Openshift offerings customer keep breaking clusters by removing default pull-secret, provided via the installer. They doing this by following:
https://docs.openshift.com/container-platform/4.3/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets

**Description:**

Cluster loses access to all secret credentials we lay down (`quay.io`, `acr`, etc)

The proposal would be to leave `pull-secret` for the customer to use and add additional secrets in the example:
```
apiVersion: v1
data:
  .dockerconfigjson: <....>
kind: Secret
metadata:
  name: rh-cloud
  namespace: openshift-config
  labels:
    config.openshift.com/pull-secret: true 
type: kubernetes.io/dockerconfigjson
```
And MCO could read all of them, and merge, where customers secret would take priority. 
This way any tooling, managed-offering, can lay their secrets and don't impact customer behaviour.
