### ISSUE TITLE
Management of non-core users

### ISSUE THREAD

**Issue by suetema** [openshift/machine-config-operator#1749]
It would be useful if the machine config operator would be able to manage more than just the `core` user. This way all management users could have their own user to log in with.
Is this a bad idea or has it just not been implemented yet?

I would define the users as follows in the ssh machineconfigs
```
      users:
      - name: core
        sshAuthorizedKeys:
        - ssh-rsa ABC123....
      - name: foo
        sshAuthorizedKeys:
        - ssh-ed25519 XYZ7890....
```
