### ISSUE TITLE
Feature request: Allow additional tolerations for machine-config-daemon

### ISSUE THREAD

**Issue by CoaxVex** [openshift/machine-config-operator#1750]
I have three machinesets to create "infra" nodes. These nodes are only meant to run infrastructure workloads such as the routers, registry, logging, monitoring, etc.
To avoid running any other workloads on them, these have a taint set:

```
  taints:
  - effect: NoExecute
    key: role
    value: infra
```

The CR's for the registry, logging, monitoring etc are then configured with an additional toleration to make sure their pods can be scheduled on these "infra" nodes.

Unfortunately, the tolerations for the machine-config-daemon daemonset seem to be hardcoded in the operator. (https://github.com/openshift/machine-config-operator/blob/master/manifests/machineconfigdaemon/daemonset.yaml)

This results in no machine-config-daemon on my infra nodes. (And also no OS upgrades for some reason.)

The workaround is to manually add the toleration to the daemonset, but this does not seem like the right approach in the long run.

Would it be possible to allow for additional tolerations? Perhaps in the MachineConfigPool CRD?

**Comment by kikisdeliveryservice** [comment]
By design, there is no intrinsic concept of infra nodes in the MCO. If you want your infra nodes to be managed by the MCO (ie manage the lifecycle of the
machines' configuration) they must be a proper custom pool ie have both "worker" and "infra" labels just like we require of any custom pool. See: https://github.com/openshift/machine-config-operator/blob/master/docs/custom-pools.md

You should be able to specify nodeSelector to then schedule onto your infra nodes:
https://docs.openshift.com/container-platform/4.4/nodes/scheduling/nodes-scheduler-default.html
https://docs.openshift.com/container-platform/4.4/nodes/scheduling/nodes-scheduler-node-selectors.html

**Comment by CoaxVex** [comment]
Without a toleration, the machine-config-daemon daemonSet will not deploy on nodes that are tainted, even if a nodeSelector is used for a custom machineConfigPool:

https://docs.openshift.com/container-platform/4.4/nodes/scheduling/nodes-scheduler-taints-tolerations.html

The DaemonSet **currently** comes with these two tolerations, which allow it to schedule on dedicated master and etcd nodes:
```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/etcd
        operator: Exists
```
What is needed, is a way to add more tolerations through a CR.

For example, the ClusterLogging custom resource allows me to do a configuration like this:
```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            memory: 1Gi 
        tolerations:
        - effect: NoExecute
          key: role
          operator: Equal
          value: infra
      rsyslog: {}
      type: fluentd
[...]
```
This results in a fluentd DaemonSet with these tolerations:
```
      tolerations:
      - effect: NoExecute
        key: role
        operator: Equal
        value: infra
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/disk-pressure
        operator: Exists
```
The node-exporter DaemonSet from openshift-monitoring works in a similar way.
