### ISSUE TITLE
MCO in OpenShift 4.3 is not able reconcile file appends with ignition 2.2

### ISSUE THREAD

**Issue by nccurry** [openshift/machine-config-operator#1847]
**Description**

I am trying to append information to a file via an OpenShift MachineConfig.

I am receiving the following error from the MacineConfigPool object

```shell
  - lastTransitionTime: "2020-06-18T17:15:47Z"
    message: 'Node ocpnonprod01azcentralusmaster2 is reporting: "can''t reconcile
      config rendered-master-ad718b514ee3eabe60296f2843eb8771 with rendered-master-8f1319b37d34d5c9857bf19b838c1f81:
      ignition file /root/test includes append: unreconcilable"'
    reason: 1 nodes are reporting degraded status on sync
    status: "True"
    type: NodeDegraded
```

My MachineConfig yaml definition is:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-test
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    storage:
      files:
      - contents:
          source: "data:,helloworld"
        append: true
        mode: 420
        path: /root/test
        filesystem: root
        user:
          name: root
        group:
          name: root
```

The comment at [pkg/daemon/update.go](https://github.com/openshift/machine-config-operator/blob/master-4.3/pkg/daemon/update.go#L403) seems to suggest this should be possible with a reprovision.

```
	// Special case files append: if the new config wants us to append, then we
	// have to force a reprovision since it's not idempotent
	for _, f := range newIgn.Storage.Files {
		if f.Append {
			return nil, fmt.Errorf("ignition file %v includes append", f.Path)
		}
	}
```

**Steps to reproduce the issue:**
1. Create machine config with file append
2. Get error

**Describe the results you received:**

Contents of ignition.spec.config.storage.files.contents.source appended to file.

**Describe the results you expected:**

Error message

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
[ncc@t490s openshift-ansible]$ oc adm release info --commits | grep machine-config-operator
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       860382c905f4358418c6513a9ab55fdd6dcc4f2d
```

**Additional environment details (platform, options, etc.):**

OpenShift BareMetal UPI 4.3.19
