### ISSUE TITLE
support some feature-gated or developer/support only osimageurl override mechanism

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#2768]
I'd like us to support *some* mechanism to override the `osImageURL` that comes from the CVO, without scaling down the CVO - i.e we'd continue to support cluster upgrades while carrying an override of the OS content.

This could take many forms; an obvious one right now is to somehow allow setting it via machineconfig.  Something like:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-mycorp-override-osimageurl
spec:
  osImageURL: quay.io/mycorp/test-os-version@sha256:...
```

But I think there needs to be some opt-in to allowing this:

 - [feature gate](https://github.com/openshift/api/blob/3cd8091317c4bf11681413843cb33ef0162ce096/config/v1/types_feature.go#L13)?  But this seems to generally block upgrades
 - Add a new CRD like `MachineConfigExperimental` ?

Is there any pattern for current platform operators to have per-operator features?
