### ISSUE TITLE
support inline data in MCs

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#283]
Ignition was designed to be a *target* for higher level config languages (e.g. `ct`).  We are currently exposing "Ignition JSON as YAML" in MCs.  I think there's no real reason for Ignition not to support true inline data (as opposed to `data:` URLs which aren't friendly to edit directly), e.g.:

```
          files:
          - contents:
              inline: |
                some inline file data here
              verification: {}
            filesystem: root
            mode: 420
            path: /etc/somefile
```

rather than requiring the `data:` URL encoding.
