### ISSUE TITLE
etcd: predicable TLS asset naming for Pod ENV

### ISSUE THREAD

**Issue by hexfusion** [openshift/machine-config-operator#325]
Currently we use ${ETCD_DNS_NAME} for naming which is fine. But to simplify debugging of etcd I would like to include helper ENV vars to the Pod for etcdctl.

If we moved the unique identifier from ETCD_DNS_NAME to metadata.name we could populate the below. Saving the user a lot of time reducing this
```
ETCDCTL_API=3 etcdctl 
--cert /etc/ssl/etcd/system:etcd-peer:sbatsche-etcd-0.devcluster.openshift.com.crt \
--key /etc/ssl/etcd/system:etcd-peer:sbatsche-etcd-0.devcluster.openshift.com.key \
--cacert /etc/ssl/etcd/ca.crt member list
```

to this
```
etcdctl member list
```

https://github.com/openshift/machine-config-operator/blob/ce2eba470b0fe85a06139d0a905b6241c5ceb409/templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml#L85-L98

proposed
```
        env:
        - name: ETCD_DATA_DIR
          value: "/var/lib/etcd"
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCDCTL_API
          value: 3
        - name: ETCDCTL_CERT
          value: "/etc/ssl/etcd/system:etcd-peer:${ETCD_NAME}.crt"
        - name: ETCDCTL_KEY 
          value: "/etc/ssl/etcd/system:etcd-peer:${ETCD_NAME}.key"
        - name: ETCDCTL_CACERT
          value: "/etc/ssl/etcd/ca.crt"
```

I am still new the this code base so I am asking for clarification on the assumptions that are made on this naming and if it is reasonable to attempt this change.
