### ISSUE TITLE
layering: pod-like MachineImage idea

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#3327]
I've been trying to sketch this out in chats around [OCP CoreOS Layering](https://github.com/openshift/enhancements/blob/master/enhancements/ocp-coreos-layering/ocp-coreos-layering.md).

Right now the API to interact is basically "override osImageURL" - all the rest of the MCO machinery then works in the same way it does today.  Most notably on this topic for example, the MCO (node controller) still owns choosing the node rollout order (i.e. which nodes get the update in what order).  This relates to https://github.com/openshift/machine-config-operator/pull/3009 as well as https://github.com/openshift/machine-config-operator/pull/2163 etc.

Once we have the "build controller" aspect of the MCO; actually ideally once we have https://github.com/openshift/machine-config-operator/issues/3137 - the admin could instead even more fully "take the wheel" and own creating something that is very much like a cut-down `Pod` to a node or a node selector, which contains the OS image they want to use:

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineImage
metadata:
  name: worker-05-image
spec:
  image: quay.io/examplecorp/rhel8-worker@sha256:...
  nodeName: worker-05
```

Here we're using `nodeName` to assign an image to a particular node.

But, it should work to use *all standard mechanisms to assign pods to nodes*, for example [node selectors](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/):

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineImage
metadata:
  name: worker-image
spec:
  image: quay.io/examplecorp/rhel8-worker@sha256:...
    matchLabels:
      node-role.kubernetes.io/worker: ""
```

I'd strawman out that once a `MachineImage` CRD is created, the MCO stops rolling out images on its own for all nodes in the pool which has any matching `MachineImage` or so.

## Pull secret

Also, we should add a [pull secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) to this CRD which allows configuring that.
