### ISSUE TITLE
when creating a new partition there is a pv inside

### ISSUE THREAD

**Issue by zfrhv** [openshift/machine-config-operator#3754]
**Description**

when creating partition using machine config, it automatically cteates physical volume inside.

its a problem because the lvm operator needs a clean partition without anything inside.

is there any way to create a clean partition without pv inside?

**Steps to reproduce the issue:**
have a disk, and split it into multiple partitions using machine config.

my machine config:
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: aa-master-disks
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      disks:
      - device: /dev/nvme0n1
        partitions:
        - label: openshift-lvm
          startMiB: 307200
          sizeMiB: 0
```

**Describe the results you received:**
i got new partition `/dev/nvme0n1p5` with a physical volume inside.
when running `pvs` i see `/dev/nvme0n1p5`

**Describe the results you expected:**
a clean partition without anything inside

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

sorry im in airgapped network and getting it out will take a while, if its really necessary i will append it later.
my version is 4.10.26

**Additional environment details (platform, options, etc.):**
