### ISSUE TITLE
Differentiate between source and rendered machineconfigs

### ISSUE THREAD

**Issue by LorbusChris** [openshift/machine-config-operator#516]
There should be a way to differentiate between supplied source and rendered machineconfigs other than their names,

e.g. through a `rendered` property on the CRD which could show up as a column on `oc get machineconfigs`.
Open to other suggestions to implement this.

**Comment by kikisdeliveryservice** [comment]
We can add a column sure, but I also think naming the generated configs something other than `worker-23409382094823904283 `would be helpful (I don't know: `worker-config-version-01` or something more human readable..) 

Along with updating the documentation to explain what the rendered master/worker config is, would go a long way to clarifying this.

**Comment by cgwalters** [comment]
Aside from the checksum, one way you know today is:

```
  ownerReferences:
  - apiVersion: machineconfiguration.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: MachineConfigPool
    name: master
    uid: 0c0c2cc8-3b8f-11e9-9ee1-664f163f5f0f
```

We could prefix them with `rendered-` maybe too?

>  `worker-config-version-01`

A lot of implications to moving away from the checksum approach.  Among other things, the bootstrap flow today relies on it.
