### ISSUE TITLE
MCD unable to "just" enable a systemd unit

### ISSUE THREAD

**Issue by JAORMX** [openshift/machine-config-operator#679]
**Description**

When providing a minimal systemd unit configuration that just "enabled" a built-in unit, the MCD is not able to start it.

**Steps to reproduce the issue:**
1. create a minimal MachineConfig object. e.g.
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 60-worker-enable-auditd
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
      - name: auditd.service
        enabled: true
```
2. apply the configuration

**Describe the results you received:**
The service wasn't started.

**Describe the results you expected:**
`systemctl status auditd` should have shown the service as started.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
  machine-config-controller                     https://github.com/openshift/machine-config-operator                       0ae25d4cd189125c981aee9bdb6d00a48ca3b978
  machine-config-daemon                         https://github.com/openshift/machine-config-operator                       0ae25d4cd189125c981aee9bdb6d00a48ca3b978
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       0ae25d4cd189125c981aee9bdb6d00a48ca3b978
  machine-config-server                         https://github.com/openshift/machine-config-operator                       0ae25d4cd189125c981aee9bdb6d00a48ca3b978
  setup-etcd-environment                        https://github.com/openshift/machine-config-operator                       0ae25d4cd189125c981aee9bdb6d00a48ca3b978
```

**Additional environment details (platform, options, etc.):**
Cluster version is 4.1.0-0.okd-2019-04-29-081740
