### ISSUE TITLE
MC spec must be required for oc create

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#777]
Haven't dug enough into this but today it's possible to successfully create the following (bad) MC:

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
 labels:
   machineconfiguration.openshift.io/role: master
 name: 99-rollback-test
spec:
config:
 ignition:
   version: 2.2.0
 storage:
   files:
   - contents:
       source: data:,A
     filesystem: root
     mode: 420
     path: /etc/rollback-test
```

It's wrongly formatted for the spec, which results in the MCC refusing to generate a new rendered one (which is good!). Still, we should have a way to prevent the creation (rolling back the above just requires oc delete badmc also).

For instance, if you create a pod w/o the spec.containers field, you'll get:
```
$ oc create -f test.yaml 
The Pod "nginx" is invalid: spec.containers: Required value
```
