### ISSUE TITLE
Ignition version validation with Kargs|FIPS

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#888]
Playing around with kargs and fips, it's not possible to just create an MC like this:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-kargs
spec:
  kargs:
    - nosmt
```

We should allow such a MC w/o incurring into ignition versions errors. It's not trivial though cause the ignition config is not a pointer so we can't really differentiate.

```
    Reason:                Failed to render configuration for pool worker: machine config: 50-kargs contains invalid ignition config: error: invalid config version (couldn't parse)
```
