### ISSUE TITLE
Show machine counts in `oc get machineconfigpools` output

### ISSUE THREAD

**Issue by ericavonb** [openshift/machine-config-operator#903]
Show the machine counts from the `machineconfigpool.status` in the `oc get machineconfigpool` output similar to the pod ready counts in deployments.

Should be as simple as adding in `additionalPrinterColumns` to the CRD:

For example, the clusteroperator resource defines extra columns like such:
```yaml
spec:
  additionalPrinterColumns:
  - JSONPath: .status.versions[?(@.name=="operator")].version
    description: The version the operator is at.
    name: Version
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].status
    description: Whether the operator is running and stable.
    name: Available
    type: string
  - JSONPath: .status.conditions[?(@.type=="Progressing")].status
    description: Whether the operator is processing changes.
    name: Progressing
    type: string
  - JSONPath: .status.conditions[?(@.type=="Degraded")].status
    description: Whether the operator is degraded.
    name: Degraded
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].lastTransitionTime
    description: The time the operator's Available status last changed.
    name: Since
    type: date
  conversion:
    strategy: None
```
